### PR TITLE
Refactored the Code and improved the Code Quality and Performance

### PR DESCRIPTION
**Pull request by HarshCasper**
This pull request fixes some of the quality issues raised by DeepSource on my fork of this repository.

Summary of fixes:

- Refactor unnecessary `else` / `elif` when `if` block has a `return` statement 
- Remove assert statement from non-test files 
- Refactor unnecessary `else` / `elif` when `if` block has a `break` statement 
- Remove implicit `object` from the base class 

You can see all the issues raised by DeepSource [here](https://deepsource.io/gh/HarshCasper/mutmut/).

These Issues were fixed automatically by DeepSource

### Using DeepSource to continuously analyze your repository

- Merge this PR. I have included a `.deepsource.toml` in this PR, which you can use to configure your analysis settings.
- Install DeepSource on your repository [here](https://deepsource.io/signup).
- Activate analysis [here](https://deepsource.io/gh/boxed/mutmut).

If you do not want to use DeepSource to continuously analyze this repo, I'll remove the `.deepsource.toml` from this PR and you can merge the rest of the fixes.

### CODE REVIEW

**Comment by boxed** [comment]
You don't seem to know python. Removing `(object)` in the inheritance is indeed reasonable as we have dropped python 2 support, but replacing it with `()` is wrong.

The rest of the changes are wrong, stupid, a matter of taste or just all of the above. Please don't submit PRs of this low quality to any other projects in the future.

**Comment by HarshCasper** [comment]
Hi, @boxed 

I definitely understand your frustration around the same, as you are the maintainer of the Project. Just to add a note here, that I did not made the changes manually, but were auto-suggested and auto-fixed by the DeepSource.

DeepSource config has a Python analyzer that detects over 520 types of issues categorized as bug-risks, anti-patterns, performance and security. The tool is free to use for open-source and is used by projects like https://github.com/uber/ludwig and https://github.com/slackapi/python-slackclient/

You can give it a try as well. If you feel that some changes are breaking the Code, do let me know so that I can report it as a False Positive and hence improve the tool further.

**Comment by boxed** [comment]
You shouldn't just spam people like this. The changes are actively bad. I don't know if they break it, but that's not really the point. You clearly haven't looked at the changes before you sent them, or you aren't competent enough to actually know if the changes are good or not. Both are very bad!

**Comment by HarshCasper** [comment]
I get your point. Can you just let me know which changes are 'bad' so that I can report the same?

**Comment by boxed** [comment]
All of it. Seriously. Every single change was wrong.

The change of `SomeClass(object):` was ALMOST correct, but it changed to `SomeClass():` but it should have changed to `SomeClass:`.

**Comment by HarshCasper** [comment]
Thanks for the suggestion. I will report it to the Engineers so that they can mark it as False Positive. 

Have a good day, Mate!

**Comment by graingert** [comment]
@HarshCasper it's not a false positive. The `(object)` is redundant on Python 2. But the parentheses are also redundant. `pyupgrade --py3-plus` will make these changes

**Pull request closed without merging**
