### PR TITLE
HTML report

### PR DESCRIPTION
**Pull request by boxed**
@s-kovacevic @nklapste check this rough draft out. Maybe @ulope is also interested?

I've attached a sample output from tri.declarative:

[html.zip](https://github.com/boxed/mutmut/files/2754678/html.zip)

### CODE REVIEW

**Comment by boxed** [comment]
(This references issue #61)

**Comment by nklapste** [comment]
I definitely like the ease of use with these html reports!

This maybe for a future PR, but, adding a line highlighting feature similar to how PIT reports would be useful. They allow for quick notation of what lines are causing mutation failures, thus, allowing a developer to quickly add the `# pragma: no mutate` as needed. As shown in the reports you generated only a small section of code (lines 764 to 864 posed problems), having a highlight of these issues could prove beneficial in giving a better visualization of failing code.

**Comment by boxed** [comment]
Highlighting the code seems like it's not really useful if you can't get at the mutants though. How about showing the full source code with color highlighting for lines that contain mutants and then allow you to click on those lines and that expands to the information in the current report (i.e. the diff and mutation id)?

**Comment by boxed** [comment]
@s-kovacevic @nklapste @sobolevn So what should we do at this point? Do you guys think my last idea for a different HTML output is better and this current version should be scrapped or should we have some different output options? Or maybe something else?

**Comment by s-kovacevic** [comment]
I think for now it is good to go, it is certanly better than nothing. However I think we should aim to improve this in future. I think this is important to improve mutmut's CI/CD capabilities. Also moving to html lib or jinja would make the code readable and easier to work with instead of inline html strings.

The original issue should probably remain open for any further discussion on how to improve HTML reports.

**Comment by fipa** [comment]
Hi, I'm starting with mutmut, moving from Java (where we have pitest) to Python and this is the one thing I'm missing. Is there any plans on moving on with this feature?

Thanks!

**Comment by boxed** [comment]
I guess. The problem i have is that I don't personally care and don't see myself using this feature so it's hard for me to know what would be a good format and design. Maybe you can provide some insight or even help design it?

**Comment by boxed** [comment]
Hmm... Reading the last comment it seems like I should merge this and make a new release and then wait for feedback. Is that a good plan for you?

**Comment by fipa** [comment]
@boxed that sounds excellent. I will use it so it won't be a problem for me to give you any feedback on the design, or maybe even PR myself.

**Comment by boxed** [comment]
This is merged and released. Give it a try! 

Note that it's super slow to generate the report. This is a general limitation in how mutmut generates mutants. It could be improved by mutating the AST, then putting it back to the state it was. Currently mutmut reparses the entire AST, which is slow (but faster than a deepcopy of the AST!).

**Pull request merged**
