### PR TITLE
Fixes #87

### LINKED ISSUE #87: mutmut does not mutate function internals
I have a simple function:

```python
def add(first: float, second: float) -> float:
     return first + second
```

And a test that ensures that it is working:

```python
# import add

def test_add():
     assert add(0, 0) == 0
```

And it works with `pytest`.

But, this should fail with `mutmut`. I expect it to change `+` -> `-`. Here's the logic that does it: https://github.com/boxed/mutmut/blob/master/mutmut/__init__.py#L293

And I expect this mutant to pass. But, nothing really happens. 
I have create a reproduction repo for you: https://github.com/sobolevn/heisenbug-2019

Here's what it outputs without cache:

```
» mutmut run

- Mutation testing starting -

These are the steps:
1. A full test suite run will be made to make sure we
   can run the tests successfully and we know how long
   it takes (to detect infinite loops for example)
2. Mutants will be generated and checked

Mutants are written to the cache in the .mutmut-cache
directory. Print found mutants with `mutmut results`.

Legend for output:
🎉 Killed mutants. The goal is for everything to end up in this bucket.
⏰ Timeout. Test suite took 10 times as long as the baseline so were killed.
🤔 Suspicious. Tests took a long time, but not long enough to be fatal.
🙁 Survived. This means your tests needs to be expanded.

mutmut cache is out of date, clearing it...
1. Running tests without mutations
⠸ Running... Done

2. Checking mutants
⠴ 0/0  🎉 0  ⏰ 0  🤔 0  🙁 0%
```

### PR DESCRIPTION
**Pull request by sobolevn**
I have test it locally, but I edited this line via github.

I will add a testcase for it later.

### CODE REVIEW

**Comment by boxed** [comment]
Hah, well that's clearly an improvement, but it does break some other things unfortunately. We need to add a rule to not mutate the return type annotation.

**Comment by sobolevn** [comment]
@boxed sure. I will work on this tomorrow.

**Comment by boxed** [comment]
@sobolevn great! Try to use the ASTPattern class. I want it to be easy to use, so any problems you'll have are very much appreciated if you can share them :P

I've also invited you to be a collaborator on mutmut now.

**Comment by sobolevn** [comment]
@boxed awesome! Thanks for inviting me 😊 

WIP

**Comment by boxed** [comment]
Ping? This seems pretty important, so if you don't have time to work on it, just say the word and I'll take over.

**Comment by sobolevn** [comment]
@boxed yes, please help me with this one. Currently I am quite busy with the business project. 😞

**Comment by boxed** [comment]
Blech, this was much more icky to fix than I'd hoped. I'll make a totally new change :(

**Comment by sobolevn** [comment]
@boxed thanks for your help!

Btw, I am making a talk about `mutmut`, I have started to work on examples: https://github.com/sobolevn/heisenbug-2019 It is an early alpha. Maybe you have some feedback about it? I would appreciate that.

**Comment by boxed** [comment]
I'll take a look!

**Pull request closed without merging**
