### PR TITLE
Improve/fix error message in get_or_guess_paths_to_mutate

### PR DESCRIPTION
**Pull request by blueyed**
btw: it displays a traceback, which is not really needed I think.

### CODE REVIEW

**Comment by boxed** [comment]
Yea the traceback isn't very useful. 

Go ahead and merge.

**Comment by boxed** [comment]
Oh, I see you haven't accepted the contributor invitation. I'll just merge then.

**Comment by blueyed** [comment]
> Oh, I see you haven't accepted the contributor invitation. I'll just merge then.

Must have missed it - normally it would show up in the web UI also, but there is none?!

**Comment by blueyed** [comment]
Nevermind, found it.
Thanks!

**Comment by boxed** [comment]
Welcome to the team!

**Pull request merged**
