### PR TITLE
Feature/refactoring rebuild

### PR DESCRIPTION
**Pull request by nklapste**
Rebuild of the refactoring and improvements from #50. 

Some changes such as using `argparse` over `click` and a improved output format have been withheld from this branch.

### Other Changes:
* simple return codes (1 if an exception was raised and 0 if the mutation tests ran without exceptions)
* added support for running on windows (tested on windows 10) (mainly fixes with opening subprocesses)
* `test_timeout` can now be executed in Travis-CI (also works in windows!)
* improved tests to be further agnostic to python version and operating system
* allowing Travis-CI to test over python versions 2.7, 3.4+, pypy2, and ~pypy3~
* `tox` is currently unused as Travis-CI and the setup.py encompass most of its functionality
* using `pylint` for linting
* `setup.py` now defines requirement data by itself

### Other Notes
* looking at the travis builds it should be further investigated on the actually usability of mutmut with python2.7
* some tests had to be modified to separate python3.6+ specific syntax checks from lower versions of python see `test_basic_mutations_python36`, `test_basic_mutations_python3`, and `test_bug_github_issue_26`

### CODE REVIEW

**Comment by boxed** [comment]
This sounds pretty great! I'll take a closer look later today.

**Comment by nklapste** [comment]
> 
> 
> This sounds pretty great! I'll take a closer look later today.

It may be beneficial to see #50 for some potentially radical changes that could be applied in the future. (e.g. new output format, advanced return codes, ect ...)

I don't want to make a huge PR so I'm probably going to hold off doing any more additions.

**Comment by boxed** [comment]
> I don't want to make a huge PR so I'm probably going to hold off doing any more additions.

I think you're past that point :P

**Comment by boxed** [comment]
What is the point of moving stuff around and making the file tree and imports complex and duplicated? You seem to be refactoring for your own aesthetics, and I don't agree with them.

This change is too big to even view properly in the GitHub interface as it stands. I appreciate the work you've put in, but you're being way too ambitious. Fixing bugs, compatibility with windows and improvements to tests (maybe) can be one PR but the refactoring you need to motivate to me.

**Comment by nklapste** [comment]
> 
> 
> What is the point of moving stuff around and making the file tree and imports complex and duplicated? You seem to be refactoring for your own aesthetics, and I don't agree with them.

Yeah having object definitions being split complicates the structure (i.e. the mutation statues being shared between the cache and mutation execution format.

I guess I've always tried to remove actual core functionality away from `__init__` and `__main__` as I've always seen them as entry points that either define the package or execution startup.

> 
> This change is too big to even view properly in the GitHub interface as it stands. I appreciate the work you've put in, but you're being way too ambitious. Fixing bugs, compatibility with windows and improvements to tests (maybe) can be one PR but the refactoring you need to motivate to me.

I'll try to separate these improvements when possible.

**Comment by boxed** [comment]
That would be great! I really appreciate the work.

**Comment by nklapste** [comment]
Move major improvements into separate PRs (#54 and #53).

**Pull request closed without merging**
