### PR TITLE
Add `mutmut show [path to file]`

### PR DESCRIPTION
**Pull request by EmilStenstrom**
This shows all diffs for the specified file. Fixes https://github.com/boxed/mutmut/issues/151

### CODE REVIEW

**Comment by boxed** [comment]
Thanks!

**Comment by EmilStenstrom** [comment]
What about making a new release with this command? Would love to run a version from pypi instead of master.

**Comment by boxed** [comment]
Sure.  I'll do it when I get to a competer.

**Comment by boxed** [comment]
Done

**Comment by EmilStenstrom** [comment]
@boxed Thanks! ⭐️

**Pull request merged**
