### PR TITLE
Feature/drop python27

### PR DESCRIPTION
**Pull request by nklapste**
Dropping Python27 and adopting more Python3-isms

This also paves the way for using `asyncio` for multiprocessed output streaming as mentioned in #103.

### CODE REVIEW

**Comment by nklapste** [comment]
@boxed Shippable keeps attempting a Python2.7 is that from configurations defined on your end?

**Comment by boxed** [comment]
Shippable is supposed to just use the travis config, so not that I'm aware of.

**Comment by nklapste** [comment]
Besides Shippable failing due to configuration that is outside of my control (and/or requiring separating our build scripts). This PR should be ready for a quick review.

Any improvements that could be onset by adopting only python3 will likely be added in future PR. This more or less removes any python2.7 fixes and mentions.

I would recommend choosing either _Travis-ci_ or Shippable maintaining both build scripts is a waste of resources.

**Comment by boxed** [comment]
Agreed. I set up shippable when the news of Travis development being gutted got out. But let's drop it until we need it.

**Comment by boxed** [comment]
The changes to .format() seems a bit silly to me. It makes more sense to change to f-strings (and require 3.6).

**Comment by blueyed** [comment]
> The changes to .format() seems a bit silly to me.

It could also just keep the percent formatting, no?
(just out of interest)

**Comment by nklapste** [comment]
> 
> 
> > The changes to .format() seems a bit silly to me.
> 
> It could also just keep the percent formatting, no?
> (just out of interest)

I've had a few issues before when debugging mutmut where the `%` formatted strings were either causing premature Exceptions or getting in the way due to typing.

I like the fact that `format` goes pretty far to try and serialize what your giving it and is less picky than `%` formatting strings on what is given (or not given).

It would be best if we adopted one form of string formatting just for code cleanliness. 

If we were to push to only support 3.6+ I would too recommend moving to f-strings.

**Pull request merged**
